"""Train the small decision tree that runs inside LLVM and write it out as C++.

Run from anywhere:  python scripts/export_tree.py
Writes patches/spill_tree.inc (pasted into RegAllocGreedy.cpp by patches/spill_predict.patch)
and results/tree_model.txt (cross-validated score and the tree in readable form).

Features are the first-visit features of data/dataset3_first.csv, over all spillable
intervals, with free registers as features (the single-model design).
"""
import os, numpy as np, pandas as pd
from sklearn.model_selection import GroupKFold
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import average_precision_score as ap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEPTH, LEAF = 6, 20

d = pd.read_csv(os.path.join(ROOT, "data", "dataset3_first.csv"))
d = d[(d.spillable == 1) & np.isfinite(d.weight)].reset_index(drop=True)
d["group"] = d.program.str.replace("_unroll", "", regex=False)
d["log_weight"] = np.log10(d.weight.clip(lower=1e-12))
d["log_size"] = np.log10(d.live_size.clip(lower=1))
d["loop_frac"] = d.loop_refs / (d.uses + d.defs).clip(lower=1)
d["free_frac"] = d.free_regs / d.total_regs.clip(lower=1)
F = ["log_weight", "segments", "log_size", "uses", "defs", "max_depth",
     "loop_frac", "crosses_mask", "total_regs", "free_regs", "free_frac"]
X, y, g = d[F].astype(float), d.spilled.values, d.group.values

def make():
    return DecisionTreeClassifier(max_depth=DEPTH, min_samples_leaf=LEAF,
                                  class_weight="balanced", random_state=0)

cv = []
for k in range(10):
    for tr, te in GroupKFold(n_splits=5, shuffle=True, random_state=k).split(X, y, g):
        cv.append(ap(y[te], make().fit(X.iloc[tr], y[tr]).predict_proba(X.iloc[te])[:, 1]))
m = make().fit(X, y)
t = m.tree_

def prob(node):
    v = t.value[node][0]
    return float(v[1] / v.sum())

def emit(node, ind):
    pad = "  " * ind
    if t.children_left[node] == -1:
        return f"{pad}return {prob(node):.17g};\n"
    f, thr = F[t.feature[node]], t.threshold[node]
    # scikit-learn compares the feature cast to float32 against a float64 threshold
    return (f"{pad}if ((double)(float)S.{f} <= {thr:.17g}) {{\n" + emit(t.children_left[node], ind + 1) +
            f"{pad}}} else {{\n" + emit(t.children_right[node], ind + 1) + f"{pad}}}\n")

code = ("// Generated by scripts/export_tree.py - do not edit by hand.\n"
        f"// DecisionTreeClassifier(max_depth={DEPTH}, min_samples_leaf={LEAF}, class_weight=balanced),\n"
        f"// trained on {len(d)} first-visit intervals. Returns the predicted probability of a spill.\n"
        "static double predictSpillTree(const SpillFeatures &S) {\n" + emit(0, 1) + "}\n")
open(os.path.join(ROOT, "patches", "spill_tree.inc"), "w").write(code)

import json
json.dump({"features": F,
           "nodes": [{"feature": (F[t.feature[i]] if t.children_left[i] != -1 else None),
                      "threshold": float(t.threshold[i]),
                      "left": int(t.children_left[i]), "right": int(t.children_right[i]),
                      "prob": prob(i)} for i in range(t.node_count)]},
          open(os.path.join(ROOT, "patches", "spill_tree.json"), "w"), indent=0)

with open(os.path.join(ROOT, "results", "tree_model.txt"), "w") as o:
    o.write(f"Decision tree depth {DEPTH}, min_samples_leaf {LEAF}, {t.node_count} nodes, {t.n_leaves} leaves\n")
    o.write(f"End-to-end PR-AUC, grouped 5-fold CV x10: {np.mean(cv):.3f} +- {np.std(cv, ddof=1):.3f} "
            f"(random {y.mean():.3f})\n\n")
    o.write(export_text(m, feature_names=F, decimals=3, show_weights=False))
print(f"nodes={t.node_count} leaves={t.n_leaves} cv PR-AUC={np.mean(cv):.3f}")
